
import { prisma } from './src/db.js';
import fetch from 'node-fetch';

const API_URL = 'http://localhost:3002'; // Adjust if needed
// You might need a valid token. For this test script, we might need a way to mock auth or login first.
// Let's assume we can use a hardcoded token or login first.

async function login() {
    // Replace with valid credentials if needed, or ensure you have a user
    let res = await fetch(`${API_URL}/auth/login`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email: 'admin@chronuscrm.com', password: 'password123' })
    });

    if (res.status === 401 || res.status === 400 || !res.ok) {
        console.log('⚠️ Login failed, attempting auto-registration...');
        const uniqueEmail = `admin-${Date.now()}@test.com`;
        res = await fetch(`${API_URL}/auth/register`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                name: 'Test Admin',
                email: uniqueEmail,
                password: 'password123'
            })
        });

        if (!res.ok) {
            const txt = await res.text();
            throw new Error(`Registration failed: ${txt}`);
        }
    }

    const data = await res.json();
    return data.token;
}

async function testErpFlow() {
    console.log('🚀 Starting ERP Flow Test...');
    let token;
    try {
        token = await login();
        console.log('✅ Auth successful (Login/Register)');
    } catch (e: any) {
        console.error('❌ Auth failed:', e.message);
        return;
    }

    const headers = {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
    };

    // 1. Create Product
    console.log('📦 Creating Product...');
    const productSku = `TEST-${Date.now()}`;
    const prodRes = await fetch(`${API_URL}/erp/products`, {
        method: 'POST',
        headers,
        body: JSON.stringify({
            name: 'Test Product Autogen',
            description: 'Generated by test script',
            price: 100,
            sku: productSku,
            stock: 50,
            imageUrl: 'https://via.placeholder.com/150'
        })
    });

    if (!prodRes.ok) throw new Error(`Create Product Failed: ${prodRes.statusText}`);
    const product = await prodRes.json();
    console.log(`✅ Product Created: ${product.id} (${product.sku})`);

    // 2. Get Customer (or create one if empty)
    const custRes = await fetch(`${API_URL}/customers`, { headers });
    let customers = await custRes.json();
    let customerId = customers[0]?.id;

    if (!customerId) {
        console.log('Creating temp customer...');
        const newCustRes = await fetch(`${API_URL}/customers`, {
            method: 'POST',
            headers,
            body: JSON.stringify({ name: 'Test Customer', email: `test${Date.now()}@example.com` })
        });
        const newCust = await newCustRes.json();
        customerId = newCust.id;
    }
    console.log(`👤 Using Customer: ${customerId}`);

    // 3. Create Order
    console.log('📝 Creating Order...');
    const orderRes = await fetch(`${API_URL}/erp/orders`, {
        method: 'POST',
        headers,
        body: JSON.stringify({
            customerId,
            items: [{ productId: product.id, quantity: 2 }]
        })
    });

    if (!orderRes.ok) throw new Error(`Create Order Failed: ${orderRes.statusText}`);
    const order = await orderRes.json();
    console.log(`✅ Order Created: ${order.id} - Total: $${order.total}`);

    // Verify totals
    if (order.total !== 200) console.error('❌ Total mismatch! Expected 200');
    else console.log('✅ Total Verified');

    // 4. Convert to Invoice
    console.log('📄 Converting to Invoice...');
    const convRes = await fetch(`${API_URL}/erp/orders/${order.id}/convert`, {
        method: 'POST',
        headers
    });

    if (!convRes.ok) throw new Error(`Convert Failed: ${convRes.statusText}`);
    const invoiceData = await convRes.json();
    console.log(`✅ Invoice Created: ${invoiceData.invoice.number}`);

    // Clean up (optional)
    console.log('🎉 ERP Flow Test Completed Successfully!');
}

testErpFlow().catch(console.error);
